// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW2nmNqFOaq-UdadneVAVZmNEu6LwKadc',
    appId: '1:241543350936:android:bd869968a7952d72069eed',
    messagingSenderId: '241543350936',
    projectId: 'chatapp-flutter-d4864',
    databaseURL: 'https://chatapp-flutter-d4864-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-flutter-d4864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVtTfcoUJ5MIECInp4eSGoswKoDjyTCI',
    appId: '1:241543350936:ios:7b52eaf89e79f2fa069eed',
    messagingSenderId: '241543350936',
    projectId: 'chatapp-flutter-d4864',
    databaseURL: 'https://chatapp-flutter-d4864-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-flutter-d4864.appspot.com',
    iosBundleId: 'com.example.chatappFlutter',
  );

}